baseURL = "https://kynrai.com/"
languageCode = "en-gb"
title = "Kynrai Digital"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "kynrai-com"
show_reading_time = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/kynrai"
  instagram = ""
  youtube = ""
  github = "https://github.com/kynrai"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/london-splash.jpg"
  recent_posts_number = 10
